services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: golang_app
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"


